---
title: "Absenteeism-and-vaccination"
author: "Alexandria C. Brown"
date: "Nov 28, 2016"
output: pdf_document
---


```{r}
library("pscl")
library("ggplot2")
library("dplyr")
library("grid")

#load("/home/alexandria/Desktop/vacc-affect-abs-model-hurdle-no-masterid.RData")
load("/home/lex/Desktop/vacc-affect-abs-model-hurdle-no-masterid.RData")

summary(AbsentModelhurd)

#load("/home/alexandria/Desktop/policy-affect-vacc-model2.RData")
load("/home/lex/Desktop/policy-affect-vacc-model2.RData")


summary(htype_model)     

```

Make some nice figures of the results.  

```{r}
vac <- summary(AbsentModelhurd)

vac_count <- data.frame(coef(vac)$count)

vac_zero <- data.frame(coef(vac)$zero)

vac_count$predictors <- rownames(vac_count)
vac_zero$predictors <- rownames(vac_zero)

vac_count <- filter(vac_count, predictors != "(Intercept)")
vac_zero <- filter(vac_zero, predictors != "(Intercept)")

vac_count$predictors <- c("2014 vs. 2013", 
                          "2015 vs. 2013", 
                          "2013 & 2014 vaccinated vs. unvaccinated",
                          "2015 vaccinated vs. unvaccinated",
                          "male vs. female", 
                          "children under 5 in household: yes vs. no",
                    "children under 5 in household: no report vs. no",
                    "URI exposure (10% increments)", 
                   "age (10 year increments)", 
                    "non-mandatory sites vs. mandatory sites")

vac_count$Estimate[vac_count$predictors=="URI exposure (10% increments)"]<- 
  vac_count$Estimate[vac_count$predictors=="URI exposure (10% increments)"]*10

vac_count$Std..Error[vac_count$predictors=="URI exposure (10% increments)"] <- 
  vac_count$Std..Error[vac_count$predictors=="URI exposure (10% increments)"]*10

vac_count$Estimate[vac_count$predictors=="age (10 year increments)"] <- 
  vac_count$Estimate[vac_count$predictors=="age (10 year increments)"]*10

vac_count$Std..Error[vac_count$predictors=="age (10 year increments)"] <- 
  vac_count$Std..Error[vac_count$predictors=="age (10 year increments)"]*10

vac_count$predictors <- factor(vac_count$predictors, levels=rev(c("2014 vs. 2013", 
                          "2015 vs. 2013", 
                          "2013 & 2014 vaccinated vs. unvaccinated",
                          "2015 vaccinated vs. unvaccinated",
                          "male vs. female", 
                          "children under 5 in household: yes vs. no",
                    "children under 5 in household: no report vs. no",
                    "URI exposure (10% increments)", 
                   "age (10 year increments)", 
                    "non-mandatory sites vs. mandatory sites")))

vac_zero$predictors <-  c("2014 vs. 2013", 
                          "2015 vs. 2013", 
                          "2013 & 2014 vaccinated vs. unvaccinated",
                          "2015 vaccinated vs. unvaccinated",
                          "male vs. female", 
                          "children under 5 in household: yes vs. no",
                    "children under 5 in household: no report vs. no",
                    "URI exposure (10% increments)", 
                   "age (10 year increments)", 
                    "non-mandatory sites vs. mandatory sites")

vac_zero$Estimate[vac_zero$predictors=="URI exposure (10% increments)"] <- 
  vac_zero$Estimate[vac_zero$predictors=="URI exposure (10% increments)"]*10

vac_zero$Std..Error[vac_zero$predictors=="URI exposure (10% increments)"] <- 
  vac_zero$Std..Error[vac_zero$predictors=="URI exposure (10% increments)"]*10

vac_zero$Estimate[vac_zero$predictors=="age (10 year increments)"] <- 
  vac_zero$Estimate[vac_zero$predictors=="age (10 year increments)"]*10

vac_zero$Std..Error[vac_zero$predictors=="age (10 year increments)"] <- 
  vac_zero$Std..Error[vac_zero$predictors=="age (10 year increments)"]*10

vac_zero$predictors <- factor(vac_zero$predictors, levels=rev(c("2014 vs. 2013", 
                          "2015 vs. 2013", 
                          "2013 & 2014 vaccinated vs. unvaccinated",
                          "2015 vaccinated vs. unvaccinated",
                          "male vs. female", 
                          "children under 5 in household: yes vs. no",
                    "children under 5 in household: no report vs. no",
                    "URI exposure (10% increments)", 
                   "age (10 year increments)", 
                    "non-mandatory sites vs. mandatory sites")))

vc <- ggplot(vac_count, aes(x=predictors, y = exp(Estimate))) +                     
  theme_bw() + 
  geom_pointrange (aes (ymin = exp(Estimate-(1.96*Std..Error)), ymax = exp(Estimate+(1.96*Std..Error)))) +              
  coord_flip() +               
  geom_hline(aes(yintercept=1), lty=2) +           
  labs(y = "Adjusted relative rate for number of days absent", x = NULL) +                 
  theme(axis.text = element_text(size=12),  axis.title=element_text(size=12,face="bold")) +
  #ggtitle("Adjusted relative rate of HCW absenteeism")+
  theme(panel.grid.minor=element_blank())+
  ylim(0.07, 2.4) 
  #scale_y_log10(limits= c(0.07, 2.4), breaks=c(0.1, 0.2, 0.4, 0.6, 0.8, 1.0, 2.0))

vz <- ggplot(vac_zero, aes(x=predictors, y = exp(Estimate))) +                         
  theme_bw() + 
  geom_pointrange (aes (ymin = exp(Estimate-(1.96*Std..Error)), ymax = exp(Estimate+(1.96*Std..Error)))) +              
  coord_flip() +               
  geom_hline(aes(yintercept=1), lty=2) +           
  labs(y = "Adjusted odds ratios for whether HCP took sick time", x = NULL) +                 
  theme(axis.text = element_text(size=12),  axis.title=element_text(size=12,face="bold")) +
  #ggtitle("Adjusted odds ratios for HCW taking any sick time")+
  theme(panel.grid.minor=element_blank()) + 
  ylim(0.07, 2.4) 
  #scale_y_log10(limits= c(0.07, 2.4), breaks=c(0.1, 0.2, 0.4, 0.6, 0.8, 1.0, 2.0))


```

Here's the figure for the model that shows whether PS hospital type is associated 
with more vaccinated participants. 

```{r}
vac <- summary(htype_model)       

vac <- data.frame(coef(vac))

vac$predictors <- rownames(vac)

vac <- filter(vac, predictors != "(Intercept)")

vac$predictors <- c("2014 vs. 2013", 
                    "2015 vs. 2013", 
                    "male vs. female",
                    "children under 5 in household: yes vs. no",
                    "children under 5 in household: no report vs. no",
                    "URI exposure (10% increments)", 
                   "age (10 year increments)", 
                    "non-mandatory sites vs. mandatory sites")

vac$predictors <- as.factor(vac$predictors)

vac$Estimate[vac$predictors=="URI exposure (10% increments)"] <- 
  vac$Estimate[vac$predictors=="URI exposure (10% increments)"]*10

vac$Std..Error[vac$predictors=="URI exposure (10% increments)"] <- 
  vac$Std..Error[vac$predictors=="URI exposure (10% increments)"]*10

vac$Estimate[vac$predictors=="age (10 year increments)"] <- 
  vac$Estimate[vac$predictors=="age (10 year increments)"]*10

vac$Std..Error[vac$predictors=="age (10 year increments)"] <- 
  vac$Std..Error[vac$predictors=="age (10 year increments)"]*10

vac$predictors <- factor(vac$predictors, levels=rev(c("2014 vs. 2013", 
                    "2015 vs. 2013", 
                    "male vs. female",
                    "children under 5 in household: yes vs. no",
                    "children under 5 in household: no report vs. no",
                    "URI exposure (10% increments)", 
                   "age (10 year increments)", 
                    "non-mandatory sites vs. mandatory sites")))

htyp <- ggplot(vac, aes(x=predictors, y = exp(vac$Estimate))) +                                                   
  theme_bw() + 
  geom_pointrange (aes (ymin = exp(Estimate-Std..Error), ymax = exp(Estimate+Std..Error))) +              
  coord_flip() +               
  geom_hline(aes(yintercept=1), lty=2) +           
  labs(y = "Adjusted odds ratios for HCP influenza vaccination", x = NULL) +                 
  theme(axis.text = element_text(size=12),  axis.title=element_text(size=12,face="bold")) +
  #ggtitle("Adjusted odds ratios for HCW influenza vaccination") +
  theme(panel.grid.minor=element_blank()) + 
  ylim(0.07, 2.4) 
  #scale_y_log10(limits= c(0.07, 2.4), breaks=c(0.1, 0.2, 0.4, 0.6, 0.8, 1.0, 2.0))

###formatting the figure

options(digits=1)

grid.newpage()
pushViewport(viewport(layout = 
                        grid.layout(nrow = 3, ncol = 2, 
                        widths = unit(c(0.05, 1), "null"))))

print(vz, vp = viewport(layout.pos.row = 2, layout.pos.col = 2))
print(vc, vp = viewport(layout.pos.row = 3, layout.pos.col = 2))
print(htyp, vp = viewport(layout.pos.row = 1, layout.pos.col = 2))
grid.text("A)", hjust=-0.25, vjust=-5.5, vp = viewport(layout.pos.row = 1, layout.pos.col = 1))
grid.text("B)", hjust=-0.25, vjust=-5.5, vp = viewport(layout.pos.row = 2, layout.pos.col = 1))
grid.text("C)", hjust=-0.25, vjust=-5.5, vp = viewport(layout.pos.row = 3, layout.pos.col = 1))
   
```






















Model diagnostics.  This is model 1 run seperately for each group, as suggested by Derek.


```{r}
load("/home/lex/Desktop/vacc-affect-abs-model1-PSonly.RData")

vacc_modelPS <- vacc_model

summary(vacc_modelPS)

load("/home/lex/Desktop/vacc-affect-abs-model1-VAonly.RData")

vacc_modelVA <- vacc_model

summary(vacc_modelVA)     
```

Make some figures of the results.  

```{r}
vac <- summary(vacc_modelVA)

vac <- data.frame(vac$solutions)

vac$predictors <- rownames(vac)

vac <- filter(vac, predictors != "(Intercept)")

vac$predictors <- c("vaccinated",
                    "male", "2014", "2015", "URI exposure", 
                    "hand hygiene", "age")

ggplot(vac, aes(x = predictors, y = post.mean)) +     
    ggtitle("Absenteeism Predictors within VA") +
  theme_bw() + 
  geom_pointrange (aes (ymin = l.95..CI, ymax = u.95..CI)) +              
  coord_flip() +               
  geom_hline(aes(yintercept=0), lty=2) +           
  labs(y = "95% CI", x = NULL) +                 
  theme(axis.text = element_text(size=12),  axis.title=element_text(size=14,face="bold"))   

vac <- summary(vacc_modelPS)

vac <- data.frame(vac$solutions)

vac$predictors <- rownames(vac)

vac <- filter(vac, predictors != "(Intercept)")

vac$predictors <- c("vaccinated",
                    "male", "2014", "2015", "URI exposure", 
                    "hand hygiene", "age")

ggplot(vac, aes(x = predictors, y = post.mean)) +                                                   
  ggtitle("Absenteeism Predictors within PS") +
  theme_bw() + 
  geom_pointrange (aes (ymin = l.95..CI, ymax = u.95..CI)) +              
  coord_flip() +               
  geom_hline(aes(yintercept=0), lty=2) +           
  labs(y = "95% CI", x = NULL) +                 
  theme(axis.text = element_text(size=12),  axis.title=element_text(size=14,face="bold"))   
```

